// backend/models/Film.js

const { Schema, model } = require("mongoose");

// Defined as its own Schema (not a plain object literal) on purpose.
// license contains a key named `type`, and Mongoose's shorthand rule reads
// ANY nested object with a `type` key as "this path's type is <that value>"
// instead of as a subdocument — so `license: { source: String, type: String, ... }`
// as a plain object was silently being read as `license: String`, discarding
// source/attributionRequired/attributionText entirely. Wrapping it in an
// explicit Schema removes that ambiguity.
const licenseSchema = new Schema(
  {
    source: String, // "archive.org", "prelinger", "loc"
    type: String, // "public-domain", "cc0", "cc-by"
    attributionRequired: Boolean,
    attributionText: String
  },
  { _id: false }
);

// Slice 15 — one entry per audio stream detected in an own-upload's
// source file by film-media-worker's buildAbrLadder.sh. `index` is the
// original ffprobe stream index (0-based, in source order); `language`
// is whatever ISO tag ffprobe found, or "und" (undetermined) if the
// source had none at all — never guessed. `label` is a display string:
// the uppercased language code if one was tagged, or "Audio 1"/"Audio 2"/
// etc in detected order if not. `isDefault` marks the one track that
// autoplays — the first stream tagged "eng" if any exists, otherwise the
// first stream by index.
const audioTrackSchema = new Schema(
  {
    index: Number,
    language: String,
    label: String,
    isDefault: Boolean
  },
  { _id: false }
);

// Slice 16 — one entry per EMBEDDED subtitle stream the source already
// carried (pure extraction, never AI-generated) that buildAbrLadder.sh
// was able to convert to WebVTT — bitmap-based codecs (PGS, VobSub) are
// skipped upstream and never produce an entry here. `index` is the
// 0-based POSITION among extracted tracks (matching the uploaded
// subs_0.vtt/subs_1.vtt/... filenames), NOT the source file's original
// subtitle-stream index — a skipped bitmap track never leaves a gap in
// this numbering. No `isDefault` field: unlike audio, subtitles are
// opt-in — none is ever auto-selected, the player starts with them off.
const subtitleTrackSchema = new Schema(
  {
    index: Number,
    language: String,
    label: String,
    key: String, // object key on storageProvider, under the film's uploads/{filmId}/hls/ prefix
    url: String // resolved public URL — populated by the ABR callback the same way renditions' playlistUrl is
  },
  { _id: false }
);

// Slice 18 — one entry per credited cast member, populated by the admin
// "Find metadata" flow (see controllers/metadataController.js) from
// TMDb's credits endpoint. Replaces the old flat string[] `cast`, which
// nothing in the app ever actually populated.
const castMemberSchema = new Schema(
  {
    name: { type: String, required: true },
    character: String,
    profileUrl: String // TMDb-hosted headshot, resolved at apply time
  },
  { _id: false }
);

const filmSchema = new Schema({
  title: { type: String, required: true, trim: true },
  originalTitle: String,
  year: Number,
  country: String,
  runtime: Number, // minutes
  category: [{ type: String, index: true }], // from fixed taxonomy (Category.name/slug) — see constants/categories.js + services/categoryMapper.js
  tags: [String], // free-text, secondary to category
  description: String,
  posterUrl: String,
  backdropUrl: String,
  cast: [castMemberSchema],
  director: String,

  license: licenseSchema,

  streamUrl: String, // the film's ORIGINAL master file. Slice 17 — no longer permanent for own-uploads: once abrStatus is "completed" AND archiveBackup.status is "completed", masterCleanupService.js clears this (and masterKey) since the HLS ladder is the playback copy from that point on. Always present and permanent for archive.org-sourced films (they have no master to clean up) and for any own-upload where ABR was skipped/never requested.
  downloadUrl: String, // normally the same file as streamUrl. Slice 17 — repointed at the flat top-quality remux (topQualityKey below) once the original master is cleaned up, so the Download button keeps working with zero frontend change either way.
  // Added for the own-upload processing pipeline (Slice 5): the 30s
  // preview clip and WebVTT captions file generated by ffmpeg/Deepgram,
  // both hosted on the same storageProvider as the master file.
  previewUrl: String,
  captionsUrl: String, // Deepgram-generated captions for the PRIMARY audio track — entirely separate from subtitleTracks below (embedded-subtitle extraction); this field and pipeline are untouched by Slice 16
  storageProvider: { type: String, enum: ["r2", "b2", "storj"], index: true }, // only set if you re-host/transcode this film yourself; absent when streamUrl just points at archive.org. Slice 17 — deliberately NEVER cleared even after the master itself is deleted: this is still needed to locate the HLS ladder folder and (if ever regenerated) to know where new output should be uploaded.
  sourceHeight: Number, // resolution of the source, reported by the existing thumbnail/preview callback — this is what lets the backend decide ABR eligibility BEFORE ever dispatching the (much longer) ABR job, with no extra probe needed
  // Size of the master/source video file in bytes. Populated by ingestion
  // (from Archive.org's file metadata) and by uploads (from the browser's
  // File object at upload time). Used to release reserved storage
  // capacity on a failed upload or (Slice 17) once the master itself is
  // cleaned up — not required elsewhere, so it's fine for this to be
  // missing on older records.
  fileSizeBytes: Number,
  transcodeStatus: { type: String, enum: ["not_started", "queued", "processing", "completed", "failed"], default: "not_started" }, // pipeline state for the FAST thumbnail/preview job (Slice 5) — separate from abrStatus below, which tracks the much longer, fully independent multi-quality (+ subtitle extraction, Slice 16) job
  // --- Slice 14: stuck-transcode reconciliation (thumbnail/preview job) ---
  // transcodeStartedAt is set at DISPATCH time (own-upload creation via
  // uploadController.createUpload, a manual admin retry via
  // uploadController.retryProcessing, or an automated retry from the
  // stuck-job sweep) — not from process-upload.yml's "running" callback.
  // This is what lets serviceController.js's reconciliation sweep measure
  // real total wait time since processing was last (re)dispatched.
  transcodeStartedAt: Date,
  // How many times the stuck-job reconciliation sweep has automatically
  // retried the thumbnail/preview job — capped at one automatic retry
  // before the sweep gives up and marks it failed. Reset to 0 by a
  // manual admin retry, since that's a deliberate fresh attempt.
  transcodeRetryCount: { type: Number, default: 0 },
  // Human-readable reason the last thumbnail/preview attempt failed.
  transcodeError: String,
  masterKey: String, // object key on storageProvider, needed for delete() — only relevant when storageProvider is set. Slice 17 — cleared (unset) once masterCleanupService.js deletes the physical object; its absence alongside a set masterDeletedAt below means "cleaned up on purpose", not "never had one".

  // --- Slice 17: master-file lifecycle ---
  // Set the moment masterCleanupService.js actually deletes the master
  // object from storage — the explicit signal that masterKey/streamUrl
  // being absent means "deliberately cleaned up", never inferred from a
  // failed download (which could just as easily mean a transient
  // storage hiccup). Permanent and never cleared once set.
  masterDeletedAt: Date,
  // Object key of the flat, single-file MP4 remux/encode of the top
  // rendition (with its default audio track muxed in, or silent for a
  // silent source) that film-media-worker's buildAbrLadder.sh produces
  // alongside the HLS ladder whenever ABR runs at all. Populated by the
  // ABR success callback the same way manifestKey/renditions are; used
  // by masterCleanupService.js to repoint downloadUrl once the original
  // master is deleted, since HLS renditions themselves are playlists +
  // segments, not single downloadable files.
  topQualityKey: String,
  // Object keys of the generated thumbnail / 30s preview / Deepgram
  // captions files. Their PUBLIC URLs were always stored (posterUrl,
  // previewUrl, captionsUrl) but never their keys — filmDeletionService
  // used to re-derive them from masterKey, which stops working once the
  // master is cleaned up. masterCleanupService.js records all three
  // (derived from masterKey using the fixed naming convention) at the
  // moment it clears masterKey, so a later permanent delete can still
  // find and remove them instead of orphaning them.
  thumbKey: String,
  previewKey: String,
  captionsKey: String,

  // --- Slice 15: adaptive bitrate (multi-resolution) + multi-audio streaming ---
  // Whether the admin left the upload form's "Generate multiple quality
  // levels" toggle on for this upload (default true). Consulted, along
  // with sourceHeight above, the moment sourceHeight becomes known (the
  // existing thumbnail/preview success callback) to decide whether to
  // dispatch the separate ABR job at all — see
  // controllers/serviceController.js's decideAndDispatchAbr.
  abrRequested: { type: Boolean, default: true },
  // "not_applicable": abrRequested was false, or this film predates
  //   the ABR pipeline / isn't an own-upload at all.
  // "skipped": abrRequested was true but sourceHeight is below the 480p
  //   floor — an honest, expected outcome, never treated as a failure.
  // "queued" / "processing": dispatched, awaiting the ABR callback.
  // "completed": manifestUrl/renditions/audioTracks/subtitleTracks/
  //   topQualityKey below are populated and ready to serve.
  // "failed": the ABR job itself failed, or a dispatch attempt failed,
  //   or the stuck-job sweep gave up on it — see abrError. The film's
  //   original direct-file playback is completely unaffected either way.
  abrStatus: {
    type: String,
    enum: ["not_applicable", "skipped", "queued", "processing", "completed", "failed"],
    default: "not_applicable"
  },
  abrError: String,
  // Set at ABR dispatch time (same "re-armed on every fresh dispatch"
  // rule as transcodeStartedAt above) — used by the stuck-job
  // reconciliation sweep with its own, longer threshold (the ABR job
  // runs far longer than the thumbnail/preview job).
  abrStartedAt: Date,
  // Total size, in bytes, of everything the ABR job wrote to storage
  // (every rendition + segment + playlist file + subtitle .vtt file +,
  // Slice 17, the flat top_quality.mp4) — reported by the ABR success
  // callback. Used to (a) count real usage against the film's
  // storageProvider (on top of fileSizeBytes, which only ever reflected
  // the original master), and (b) release that same amount back on
  // deletion (see services/filmDeletionService.js). Absent unless
  // abrStatus is "completed".
  abrOutputBytes: Number,
  // The HLS master playlist's public URL — populated by the ABR success
  // callback. Absent unless abrStatus is "completed" — the frontend
  // player treats its absence as "no ABR available, use the direct
  // file" in every case.
  manifestUrl: String,
  // One entry per resolution rung actually produced. codec is always
  // "h264" (no HEVC/AV1 support yet — not a stated need).
  renditions: [{
    resolution: String, // "1080p", "720p", "480p"
    height: Number,
    bitrateKbps: Number,
    playlistUrl: String,
    key: String, // object key on storageProvider
    segmentCount: Number,
    codec: { type: String, default: "h264" }
  }],
  // One entry per audio stream detected in the source — empty/absent
  // for single-audio sources (nothing to select between) and for any
  // film with abrStatus other than "completed".
  audioTracks: [audioTrackSchema],
  // Slice 16 — one entry per embedded, text-based subtitle stream the
  // source already carried, extracted (never generated) by the same ABR
  // job. Empty/absent for sources with no usable embedded subtitles, and
  // for any film with abrStatus other than "completed" — same absence
  // convention as audioTracks/renditions above.
  subtitleTracks: [subtitleTrackSchema],

  archiveBackup: { // insurance mirror of YOUR re-hosted copy — separate from `archiveIdentifier` below, which is the SOURCE item you pulled from archive.org. Never touched by masterCleanupService — deletion only ever CONSUMES this field's status, it never writes to it.
    pushed: { type: Boolean, default: false },
    archiveIdentifier: String,
    pushedDate: Date,
    status: { type: String, enum: ["pending", "completed", "failed"], default: "pending" },
    // Set when an attempt actually STARTS (the schema default of
    // status "pending" applies to every film, including ones that never
    // attempt a backup at all, so status alone can't distinguish "in
    // flight" from "never tried"). Lets the reconciliation sweep spot an
    // attempt that died with the server mid-upload and flip it to
    // "failed" so the Retry backup button becomes available.
    startedAt: Date,
    error: String
  },
  fileHash: String, // SHA-256-derived fingerprint (own-uploads: see lib/fileFingerprint.ts; ingestion: hash of the archive.org identifier), for dedup — indexed below (unique+sparse), not inline

  status: { type: String, enum: ["pending", "approved", "rejected"], default: "pending" }, // indexed below as part of the compound browse index
  verifiedBy: String,
  verifiedDate: Date,
  region: { type: String, default: "US" },

  linkHealth: {
    lastChecked: Date,
    isHealthy: { type: Boolean, default: true },
    lastError: String
  },

  // --- Slice 18: movie metadata (admin-confirmed TMDb match) ---
  // Populated ONLY by the admin "Find metadata" flow — never by a
  // background sync — and only after the admin confirmed the match.
  tmdbId: Number,
  imdbId: String,
  // YouTube video id (not a full URL) of the trailer. trailerSource is
  // "tmdb" when TMDb's own /videos listed one, "youtube" when it came
  // from the search fallback (only ever called when TMDb had none).
  trailerYoutubeKey: String,
  trailerSource: { type: String, enum: ["tmdb", "youtube"] },
  ratings: {
    tmdb: Number, // 0-10, from TMDb at apply time
    imdb: Number, // 0-10, from OMDb ("Fetch ratings" action)
    rottenTomatoes: Number, // 0-100
    metascore: Number, // 0-100
    fetchedAt: Date
  },
  metadataSource: { type: String, enum: ["tmdb"] },
  metadataEnrichedAt: Date,

  embeddingId: String, // reference to Qdrant vector point ID
  source: { type: String, enum: ["archive.org", "own-upload"] },
  archiveIdentifier: String, // Archive.org's own item ID — indexed below (unique+sparse), not inline

  views: { type: Number, default: 0 },
  avgRating: { type: Number, default: 0 }, // denormalized from Review, updated on write
  ratingCount: { type: Number, default: 0 },

  addedDate: { type: Date, default: Date.now },
  updatedDate: Date
});

// --- Indexes ---
// dedup: never insert the same physical file twice
filmSchema.index({ fileHash: 1 }, { unique: true, sparse: true });
// dedup against re-runs of the same archive.org item
filmSchema.index({ archiveIdentifier: 1 }, { unique: true, sparse: true });
// browse/filter: "approved films in category X, newest first"
filmSchema.index({ status: 1, category: 1, addedDate: -1 });
// text search fallback (Qdrant handles semantic search; this covers exact/keyword search)
filmSchema.index({ title: "text", originalTitle: "text", tags: "text", description: "text" });
// link-health sweep job
filmSchema.index({ "linkHealth.isHealthy": 1, "linkHealth.lastChecked": 1 });
// stuck-job reconciliation sweep (Slice 14): thumbnail/preview jobs
filmSchema.index({ transcodeStatus: 1, transcodeStartedAt: 1 });
// stuck-job reconciliation sweep (Slice 15): ABR jobs — same shape as
// the index above, separate because these are two independent pipelines
// with two independent "processing" states.
filmSchema.index({ abrStatus: 1, abrStartedAt: 1 });

module.exports = model("Film", filmSchema);
